// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/snapshot/bootstrap/interfaces.go

// Package bootstrap is a generated GoMock package.
package bootstrap

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/pingcap/ticdc/pkg/common"
	protocol "github.com/pingcap/ticdc/pkg/snapshot/protocol"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// LoadSnapshot mocks base method.
func (m *MockRepository) LoadSnapshot(arg0 context.Context, arg1 common.ChangeFeedID, arg2 uint64) (*protocol.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSnapshot", arg0, arg1, arg2)
	ret0, _ := ret[0].(*protocol.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSnapshot indicates an expected call of LoadSnapshot.
func (mr *MockRepositoryMockRecorder) LoadSnapshot(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSnapshot", reflect.TypeOf((*MockRepository)(nil).LoadSnapshot), arg0, arg1, arg2)
}

// SaveSnapshot mocks base method.
func (m *MockRepository) SaveSnapshot(arg0 context.Context, arg1 common.ChangeFeedID, arg2 uint64, arg3 *protocol.State) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSnapshot", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSnapshot indicates an expected call of SaveSnapshot.
func (mr *MockRepositoryMockRecorder) SaveSnapshot(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSnapshot", reflect.TypeOf((*MockRepository)(nil).SaveSnapshot), arg0, arg1, arg2, arg3)
}

// MockCapture is a mock of Capture interface.
type MockCapture struct {
	ctrl     *gomock.Controller
	recorder *MockCaptureMockRecorder
}

// MockCaptureMockRecorder is the mock recorder for MockCapture.
type MockCaptureMockRecorder struct {
	mock *MockCapture
}

// NewMockCapture creates a new mock instance.
func NewMockCapture(ctrl *gomock.Controller) *MockCapture {
	mock := &MockCapture{ctrl: ctrl}
	mock.recorder = &MockCaptureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapture) EXPECT() *MockCaptureMockRecorder {
	return m.recorder
}

// AbortSnapshot mocks base method.
func (m *MockCapture) AbortSnapshot(arg0 common.ChangeFeedID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AbortSnapshot", arg0)
}

// AbortSnapshot indicates an expected call of AbortSnapshot.
func (mr *MockCaptureMockRecorder) AbortSnapshot(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortSnapshot", reflect.TypeOf((*MockCapture)(nil).AbortSnapshot), arg0)
}

// ApplySnapshot mocks base method.
func (m *MockCapture) ApplySnapshot(arg0 context.Context, arg1 common.ChangeFeedID, arg2 uint64, arg3 protocol.Spec, arg4 protocol.ObjectRef, arg5 protocol.Export) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySnapshot", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplySnapshot indicates an expected call of ApplySnapshot.
func (mr *MockCaptureMockRecorder) ApplySnapshot(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySnapshot", reflect.TypeOf((*MockCapture)(nil).ApplySnapshot), arg0, arg1, arg2, arg3, arg4, arg5)
}

// DrainSnapshot mocks base method.
func (m *MockCapture) DrainSnapshot(arg0 context.Context, arg1 common.ChangeFeedID, arg2 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrainSnapshot", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DrainSnapshot indicates an expected call of DrainSnapshot.
func (mr *MockCaptureMockRecorder) DrainSnapshot(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainSnapshot", reflect.TypeOf((*MockCapture)(nil).DrainSnapshot), arg0, arg1, arg2)
}
